version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    labels:
      - "ci"
  - package-ecosystem: "gitsubmodule"
    directory: "/3rdParty"
    schedule:
      interval: "daily"
    labels:
      - "submodules"