#include "widgets/settingspages/HighlightsBetaConfigureDialog.hpp"

#include <qboxlayout.h>
#include <qcheckbox.h>
#include <qdialogbuttonbox.h>
#include <qformlayout.h>
#include <qgroupbox.h>
#include <qlabel.h>
#include <qlineedit.h>
#include <qnamespace.h>
#include <qtextedit.h>

namespace chatterino {

using namespace Qt::StringLiterals;

HighlightsBetaConfigureDialog::HighlightsBetaConfigureDialog(
    HighlightData _data, QWidget *parent)
    : BasePopup(
          {
              BaseWindow::EnableCustomFrame,
              BaseWindow::DisableLayoutSave,
              BaseWindow::BoundsCheckOnShow,
          },
          parent)
    , data(std::move(_data))
{
    this->setWindowTitle(u"Chatterino - Highlight editor"_s);
    this->setAttribute(Qt::WA_DeleteOnClose);

    auto *dialogLayout = new QVBoxLayout;

    // TODO
    // Name of the highlight
    // This should be autogenerated, with the option to "revert back" to the default name if a
    // user no longer wants to use a custom name for it.
    // This should work as closely as possible to the tab naming feature.

    // TODO
    // An enabled toggle
    // Is "Active" a better phrase for this?

    // TODO
    // The highlight pattern
    // The default case should preferably always be text matching
    // We should provide some functionality underneath this or nearby this to highlight on badges I think

    // this->setLayout(layout);
    auto *formLayout = new QFormLayout;
    formLayout->addRow("Pattern", new QLineEdit());

    dialogLayout->addLayout(formLayout);

    // TODO
    // Group of side effects
    //  - Show message in mentions
    //  - Highlight message
    //  - Flash taskbar
    //  - Not implemented but highlight portion of message?
    //  - Play sound (default sound? custom sound url?)
    {
        auto *group = new QGroupBox("Side effects");

        auto *l = new QFormLayout;
        l->addRow("Show message in mentions", new QCheckBox());
        l->addRow("Highlight message", new QCheckBox());
        l->addRow("Flash taskbar", new QCheckBox());
        l->addRow("Play sound", new QCheckBox());
        l->addRow("Custom sound URL", new QLineEdit());

        group->setLayout(l);

        dialogLayout->addWidget(group);
    }

    auto *buttonBox =
        new QDialogButtonBox(QDialogButtonBox::Ok | QDialogButtonBox::Cancel);

    QObject::connect(buttonBox, &QDialogButtonBox::accepted, this, [this] {
        Q_EMIT this->confirmed(this->data);  // XD
        this->close();
    });
    QObject::connect(buttonBox, &QDialogButtonBox::rejected, this,
                     &BasePopup::close);
    dialogLayout->addWidget(buttonBox, 0, Qt::AlignRight);

    this->setLayout(dialogLayout);
}

}  // namespace chatterino
