#include "widgets/settingspages/HighlightsBetaConfigureDialog.hpp"

#include "widgets/Label.hpp"

#include <qboxlayout.h>
#include <qcheckbox.h>
#include <qdialogbuttonbox.h>
#include <qformlayout.h>
#include <qgroupbox.h>
#include <qlabel.h>
#include <qlineedit.h>
#include <qnamespace.h>
#include <qtextedit.h>
#include <QToolButton>

namespace chatterino {

using namespace Qt::StringLiterals;

namespace {

auto makeCheckbox(bool &value)
{
    auto *w = new QCheckBox();
    w->setChecked(value);

    QObject::connect(w, &QCheckBox::checkStateChanged, [&](auto checkstate) {
        value = checkstate == Qt::CheckState::Checked;
    });
    return w;
}

auto makeLineEdit(QString &value)
{
    auto *w = new QLineEdit();
    w->setText(value);
    QObject::connect(w, &QLineEdit::textChanged, [&](const auto &newText) {
        value = newText;
    });
    return w;
}

}  // namespace

HighlightsBetaConfigureDialog::HighlightsBetaConfigureDialog(
    SharedHighlight _data, QWidget *parent)
    : BasePopup(
          {
              BaseWindow::EnableCustomFrame,
              BaseWindow::DisableLayoutSave,
              BaseWindow::BoundsCheckOnShow,
          },
          parent)
    , data(std::move(_data))
{
    this->setWindowTitle(u"Chatterino - Highlight editor"_s);
    this->setAttribute(Qt::WA_DeleteOnClose);

    this->resize(515, 600);

    auto *dialogLayout = new QVBoxLayout;

    // TODO
    // Name of the highlight
    // This should be autogenerated, with the option to "revert back" to the default name if a
    // user no longer wants to use a custom name for it.
    // This should work as closely as possible to the tab naming feature.

    // TODO
    // An enabled toggle
    // Is "Active" a better phrase for this?

    // TODO
    // The highlight pattern
    // The default case should preferably always be text matching
    // We should provide some functionality underneath this or nearby this to highlight on badges I think

    // this->setLayout(layout);
    auto *formLayout = new QFormLayout;
    formLayout->addRow("Name", makeLineEdit(this->data.name));
    formLayout->addRow("Pattern", makeLineEdit(this->data.pattern));
    formLayout->addRow("Enabled", makeCheckbox(this->data.enabled));

    dialogLayout->addLayout(formLayout);

    // TODO: Allow for customization of highlight color

    // TODO
    // Group of side effects
    //  - Show message in mentions
    //  - Highlight message
    //  - Flash taskbar
    //  - Not implemented but highlight portion of message?
    //  - Play sound (default sound? custom sound url?)
    {
        auto *group = new QGroupBox("Side effects");

        auto *l = new QFormLayout;
        l->addRow("Show message in mentions",
                  makeCheckbox(this->data.showInMentions));
        // l->addRow("Highlight message", makeCheckbox(this->data.));
        l->addRow("Enable regex", makeCheckbox(this->data.isRegex));
        l->addRow("Case sensitive", makeCheckbox(this->data.isCaseSensitive));
        l->addRow("Flash taskbar", makeCheckbox(this->data.alert));
        l->addRow("Play sound", makeCheckbox(this->data.playSound));

        {
            auto *ll = new QHBoxLayout;

            auto *label = new QLabel(this->data.customSoundURL.toLocalFile());
            ll->addWidget(label);

            auto *edit = new QToolButton;
            edit->setIcon(QIcon(":/buttons/edit.svg"));
            ll->addWidget(edit);
            // TODO: Implement Edit

            auto *clear = new QToolButton;
            clear->setIcon(QIcon(":/buttons/cancel.svg"));
            ll->addWidget(clear);

            // TODO: Implement clear

            l->addRow(new QLabel("Custom sound URL"));
            l->addRow(ll);
        }

        group->setLayout(l);

        dialogLayout->addWidget(group);
    }

    auto *buttonBox =
        new QDialogButtonBox(QDialogButtonBox::Ok | QDialogButtonBox::Cancel);

    QObject::connect(buttonBox, &QDialogButtonBox::accepted, this, [this] {
        Q_EMIT this->confirmed(this->data);
        this->close();
    });
    QObject::connect(buttonBox, &QDialogButtonBox::rejected, this,
                     &BasePopup::close);
    dialogLayout->addWidget(buttonBox, 0, Qt::AlignRight);

    this->setLayout(dialogLayout);
}

}  // namespace chatterino
