freebsd_instance:
  image_family: freebsd-14-0

task:
  install_script:
    - pkg install -y boost-libs git qt6-base qt6-svg qt6-5compat qt6-imageformats qtkeychain-qt6 cmake
  script: |
    git submodule init
    git submodule update
    mkdir build
    cd build
    c++ --version
    cmake \
        -DCMAKE_C_COMPILER="cc" \
        -DCMAKE_CXX_COMPILER="c++" \
        -DCMAKE_C_FLAGS="-O2 -pipe  -fstack-protector-strong -fno-strict-aliasing "  \
        -DCMAKE_CXX_FLAGS="-O2 -pipe -fstack-protector-strong -fno-strict-aliasing  " \
        -DLINK_OPTIONS="-fstack-protector-strong" \
        -DCMAKE_INSTALL_PREFIX="/usr/local" \
        -DUSE_SYSTEM_QTKEYCHAIN="ON" \
        -DCMAKE_BUILD_TYPE="release" \
        -DCMAKE_EXPORT_COMPILE_COMMANDS="ON" \
        -DBUILD_WITH_QT6="ON" \
        ..
    cat compile_commands.json
    make -j $(getconf _NPROCESSORS_ONLN)
