comment: false
ignore:
  - "**/usr/local*/**/*"
  - "**/usr/include/**/*"
  - "**/lib/certify/*"
  - "**/lib/expected-lite/*"
  - "**/lib/googletest/*"
  - "**/lib/libcommuni/*"
  - "**/lib/lrucache/*"
  - "**/lib/lua/*"
  - "**/lib/magic_enum/*"
  - "**/lib/miniaudio/*"
  - "**/lib/qtkeychain/*"
  - "**/lib/rapidjson/*"
  - "**/lib/semver/*"
  - "**/lib/serialize/*"
  - "**/lib/settings/*"
  - "**/lib/signals/*"
  - "**/lib/sol2/*"
  - "**/lib/websocketpp/*"
  - "**/lib/WinToast/*"
  - "**/build*/"
  - "**/ui_*.h"
  - "**/moc_*.cpp"
fixes:
  - "__w/chatterino2/chatterino2/::"
