#include "controllers/highlights/ConfigureDialog.hpp"

#include "Application.hpp"
#include "providers/twitch/TwitchBadges.hpp"
#include "util/DisplayBadge.hpp"
#include "util/Variant.hpp"
#include "widgets/dialogs/ColorPickerDialog.hpp"
#include "widgets/helper/color/ColorButton.hpp"

#include <qboxlayout.h>
#include <qcheckbox.h>
#include <QComboBox>
#include <qdialogbuttonbox.h>
#include <QFileDialog>
#include <qformlayout.h>
#include <qgroupbox.h>
#include <qlabel.h>
#include <qlineedit.h>
#include <qnamespace.h>
#include <qsizepolicy.h>
#include <qtextedit.h>
#include <QToolButton>

namespace chatterino::highlights {

template <typename T>
concept SupportsCaseSensitivity = requires(T a) {
    { a.isCaseSensitive() } -> std::same_as<bool>;
    { a.setCaseSensitive(true) };
};

template <typename T>
concept SupportsRegex = requires(T a) {
    { a.isRegex() } -> std::same_as<bool>;
    { a.setRegex(true) };
};

template <typename T>
concept SupportsDefaultName = requires(T a) {
    { a.getDefaultName() } -> std::same_as<QString>;
};

using namespace Qt::StringLiterals;

namespace {

// Add additional badges for highlights here
const QList<DisplayBadge> AVAILABLE_BADGES = {
    {"Broadcaster", "broadcaster"},
    {"Admin", "admin"},
    {"Staff", "staff"},
    {"Moderator", "moderator"},
    {"Lead Moderator", "lead_moderator"},
    {"Verified", "partner"},
    {"VIP", "vip"},
    {"Founder", "founder"},
    {"Subscriber", "subscriber"},
    {"Predicted Blue", "predictions/blue-1,predictions/blue-2"},
    {"Predicted Pink", "predictions/pink-2,predictions/pink-1"},
};

auto makeCheckbox(bool &value)
{
    auto *w = new QCheckBox();
    w->setChecked(value);

    QObject::connect(w, &QCheckBox::checkStateChanged, [&](auto checkstate) {
        value = checkstate == Qt::CheckState::Checked;
    });
    return w;
}

auto makeLineEdit(QString &value)
{
    auto *w = new QLineEdit();
    w->setText(value);
    QObject::connect(w, &QLineEdit::textChanged, [&](const auto &newText) {
        value = newText;
    });
    return w;
}

}  // namespace

ConfigureDialog::ConfigureDialog(AllHighlights _data, QWidget *parent)
    : BasePopup(
          {
              BaseWindow::EnableCustomFrame,
              BaseWindow::DisableLayoutSave,
              BaseWindow::BoundsCheckOnShow,
          },
          parent)
    , data(std::move(_data))
{
    this->setWindowTitle(u"Chatterino - Highlight editor"_s);
    this->setAttribute(Qt::WA_DeleteOnClose);

    this->resize(515, 500);

    auto *dialogLayout = new QVBoxLayout;

    // TODO
    // Name of the highlight
    // This should be autogenerated, with the option to "revert back" to the default name if a
    // user no longer wants to use a custom name for it.
    // This should work as closely as possible to the tab naming feature.

    // TODO
    // An enabled toggle
    // Is "Active" a better phrase for this?

    // TODO
    // The highlight pattern
    // The default case should preferably always be text matching
    // We should provide some functionality underneath this or nearby this to highlight on badges I think

    // this->setLayout(layout);
    auto *formLayout = new QFormLayout;

#ifndef NDEBUG
    {
        auto value = std::visit(
            [](auto &&h) {
                return h.getID();
            },
            this->data);
        auto *w = new QLabel(value.toString());
        w->setTextInteractionFlags(Qt::TextSelectableByMouse);
        formLayout->addRow("ID", w);
    }
#endif

    {
        auto value = std::visit(
            [](auto &&h) {
                return h.name;
            },
            this->data);
        auto *w = new QLineEdit();
        formLayout->addRow("Name", w);

        std::visit(variant::Overloaded{
                       [w](SupportsDefaultName auto &h) {
                           w->setPlaceholderText(h.getDefaultName());
                           w->setText(h.name);

                           QObject::connect(w, &QLineEdit::textChanged,
                                            [&](const auto &newText) {
                                                h.name = newText;
                                            });
                       },
                       [w](auto &&h) {
                           w->setPlaceholderText("b");
                           w->setText(h.name);

                           QObject::connect(w, &QLineEdit::textChanged,
                                            [&](const auto &newText) {
                                                h.name = newText;
                                            });
                       },
                   },
                   this->data);
    }

    std::visit(
        variant::Overloaded{
            [formLayout](FilterHighlight &h) {
                auto *w = new QLineEdit();
                w->setText(h.filterText);
                QObject::connect(w, &QLineEdit::textChanged,
                                 [&](const auto &newText) {
                                     h.setFilterText(newText);
                                 });
                formLayout->addRow("Filter", w);
            },
            [formLayout](BadgeHighlight &h) {
                auto *w = new QComboBox();
                for (const auto &item : AVAILABLE_BADGES)
                {
                    w->addItem(item.displayName(), item.badgeName());
                }

                QObject::connect(
                    w, QOverload<int>::of(&QComboBox::currentIndexChanged),
                    [&h](int index) {
                        std::optional<DisplayBadge> badge;
                        if (index >= 0 && index < AVAILABLE_BADGES.size())
                        {
                            badge = AVAILABLE_BADGES[index];
                            h.setBadgeName(badge->badgeName());
                            h.setDisplayName(badge->displayName());
                        }
                    });

                w->setCurrentText(h.displayName);

                getApp()->getTwitchBadges()->getBadgeIcons(
                    AVAILABLE_BADGES,
                    [w](QString identifier, const std::shared_ptr<QIcon> icon) {
                        if (!w)
                        {
                            return;
                        }

                        int index = w->findData(identifier);
                        if (index != -1)
                        {
                            w->setItemIcon(index, *icon);
                        }
                    });
                formLayout->addRow("Badge", w);
            },
            [formLayout](UserHighlight &h) {
                auto *w = new QLineEdit();
                w->setText(h.username);
                QObject::connect(w, &QLineEdit::textChanged,
                                 [&](const auto &newText) {
                                     h.username = newText;
                                 });
                formLayout->addRow("Username", w);
            },
            [formLayout](MessageHighlight &h) {
                auto *w = new QLineEdit();
                w->setText(h.pattern);
                QObject::connect(w, &QLineEdit::textChanged,
                                 [&](const auto &newText) {
                                     h.pattern = newText;
                                 });
                formLayout->addRow("Pattern", w);
            },
            [&](auto &&) {
                //default xd
            },
        },
        this->data);

    {
        auto value = std::visit(
            [](auto &&h) {
                return h.isEnabled();
            },
            this->data);
        auto *w = new QCheckBox;
        w->setChecked(value);

        QObject::connect(w, &QCheckBox::checkStateChanged,
                         [&](auto checkstate) {
                             std::visit(
                                 [checkstate](auto &&h) {
                                     h.enabled = checkstate;
                                 },
                                 this->data);
                         });
        formLayout->addRow("Enabled", w);
    }

    dialogLayout->addLayout(formLayout);

    // TODO: Allow for customization of highlight color

    // TODO
    // Group of side effects
    //  - Show message in mentions
    //  - Highlight message
    //  - Flash taskbar
    //  - Not implemented but highlight portion of message?
    //  - Play sound (default sound? custom sound url?)
    {
        auto *group = new QGroupBox("Side effects");

        auto *l = new QFormLayout;
        {
            auto value = std::visit(
                [](auto &&h) {
                    return h.shouldShowInMentions();
                },
                this->data);
            auto *w = new QCheckBox;
            w->setChecked(value);

            QObject::connect(w, &QCheckBox::checkStateChanged,
                             [&](auto checkstate) {
                                 std::visit(
                                     [checkstate](auto &&h) {
                                         h.setShowInMentions(checkstate);
                                     },
                                     this->data);
                             });
            l->addRow("Show message in mentions", w);
        }

        std::visit(variant::Overloaded{
                       [&](SupportsRegex auto &h) {
                           auto *w = new QCheckBox;
                           w->setChecked(h.isRegex());
                           QObject::connect(w, &QCheckBox::checkStateChanged,
                                            [&](auto checkstate) {
                                                h.setRegex(checkstate);
                                            });
                           l->addRow("Enable regex", w);
                       },
                       [&](auto &&) {},
                   },
                   this->data);

        std::visit(variant::Overloaded{
                       [&](SupportsCaseSensitivity auto &h) {
                           auto *w = new QCheckBox;
                           w->setChecked(h.isCaseSensitive());
                           QObject::connect(w, &QCheckBox::checkStateChanged,
                                            [&](auto checkstate) {
                                                h.setCaseSensitive(checkstate);
                                            });
                           l->addRow("Case sensitive", w);
                       },
                       [&](auto &&) {},
                   },
                   this->data);

        {
            auto value = std::visit(
                [](auto &&h) {
                    return h.shouldHighlightTaskbar();
                },
                this->data);
            auto *w = new QCheckBox;
            w->setChecked(value);

            QObject::connect(w, &QCheckBox::checkStateChanged,
                             [&](auto checkstate) {
                                 std::visit(
                                     [checkstate](auto &&h) {
                                         h.setHighlightTaskbar(checkstate);
                                     },
                                     this->data);
                             });
            l->addRow("Flash taskbar", w);
        }

        {
            auto value = std::visit(
                [](auto &&h) {
                    return *h.getBackgroundColor();
                },
                this->data);
            auto *w = new ColorButton(value);
            w->setSizePolicy(QSizePolicy::Minimum, QSizePolicy::Minimum);

            QObject::connect(w, &ColorButton::clicked, [this, w]() {
                auto value = std::visit(
                    [](auto &&h) {
                        return *h.getBackgroundColor();
                    },
                    this->data);
                auto *dialog = new ColorPickerDialog(value, w);
                // TODO: confirm colorButton & setting are never deleted and the signal is deleted
                // once the dialog is closed
                QObject::connect(dialog, &ColorPickerDialog::colorConfirmed, w,
                                 [this, w](auto selected) {
                                     if (selected.isValid())
                                     {
                                         w->setColor(selected);
                                         std::visit(
                                             [selected](auto &&h) {
                                                 h.setBackgroundColor(selected);
                                             },
                                             this->data);
                                     }
                                 });
                // dialog->setWindowModality(Qt::WindowModality::ApplicationModal);
                dialog->show();
            });
            l->addRow("Background color", w);
        }

        {
            auto value = std::visit(
                [](auto &&h) {
                    return h.shouldPlaySound();
                },
                this->data);
            auto *w = new QCheckBox;
            w->setChecked(value);

            QObject::connect(w, &QCheckBox::checkStateChanged,
                             [&](auto checkstate) {
                                 std::visit(
                                     [checkstate](auto &&h) {
                                         h.setPlaySound(checkstate);
                                     },
                                     this->data);
                             });
            l->addRow("Play sound", w);
        }

        {
            auto *ll = new QHBoxLayout;

            auto value = std::visit(
                [](auto &&h) {
                    return h.getSoundUrl();
                },
                this->data);

            qInfo() << "XXX: Sound URL:" << value;

            auto *label = new QLabel(value.toLocalFile());
            ll->addWidget(label);

            auto *edit = new QToolButton;
            edit->setIcon(QIcon(":/buttons/edit.svg"));
            ll->addWidget(edit);
            QObject::connect(edit, &QToolButton::clicked, [this, label] {
                auto fileUrl = QFileDialog::getOpenFileUrl(
                    this, tr("Open Sound"), QUrl(),
                    tr("Audio Files (*.mp3 *.wav)"));
                label->setText(fileUrl.toLocalFile());
                std::visit(
                    [fileUrl](auto &&h) {
                        h.setSoundUrl(fileUrl);
                    },
                    this->data);
            });
            // TODO: Implement Edit

            auto *clear = new QToolButton;
            clear->setIcon(QIcon(":/buttons/cancel.svg"));
            ll->addWidget(clear);
            QObject::connect(clear, &QToolButton::clicked, [this, label] {
                label->setText({});
                std::visit(
                    [](auto &&h) {
                        h.setSoundUrl({});
                    },
                    this->data);
            });

            // TODO: Implement clear

            l->addRow(new QLabel("Custom sound URL"));
            l->addRow(ll);
        }

        group->setLayout(l);

        dialogLayout->addWidget(group);
    }

    auto *buttonBox =
        new QDialogButtonBox(QDialogButtonBox::Ok | QDialogButtonBox::Cancel);

    QObject::connect(buttonBox, &QDialogButtonBox::accepted, this, [this] {
        Q_EMIT this->confirmed(this->data);
        this->close();
    });
    QObject::connect(buttonBox, &QDialogButtonBox::rejected, this,
                     &BasePopup::close);
    dialogLayout->addWidget(buttonBox, 0, Qt::AlignRight);

    this->setLayout(dialogLayout);
}

}  // namespace chatterino::highlights
