ARG UBUNTU_VERSION=22.04

FROM chatterino-ubuntu-$UBUNTU_VERSION-qt6-build

# In CI, this is set from the aqtinstall action
ENV Qt6_DIR=/opt/qt/6.2.4/gcc_64

WORKDIR /src/build

ADD .CI /src/.CI

# Install dependencies necessary for AppImage packaging
RUN apt-get update && apt-get -y install --no-install-recommends \
        curl \
        libxcb-shape0 \
        libfontconfig1 \
        file

# package deb
RUN ./../.CI/CreateUbuntuDeb.sh

# package appimage
RUN ./../.CI/CreateAppImage.sh
