FROM chatterino-ubuntu-20.04-build

# In CI, this is set from the aqtinstall action
ENV Qt5_DIR=/opt/qt512

WORKDIR /src/build

ADD .CI /src/.CI

# Install dependencies necessary for AppImage packaging
RUN apt-get update && apt-get -y install --no-install-recommends \
        curl \
        libfontconfig \
        libxrender1 \
        file

# package deb
RUN ./../.CI/CreateUbuntuDeb.sh

# package appimage
RUN ./../.CI/CreateAppImage.sh
