# SPDX-FileCopyrightText: 2026 Rasmus Karlsson <rasmus.karlsson@pajlada.com>
# SPDX-License-Identifier: CC0-1.0

version = 1

[[annotations]]
path = "checkmark-circle.svg"
SPDX-FileCopyrightText = "Copyright (c) 2020 Microsoft Corporation"
SPDX-License-Identifier = "MIT"

[[annotations]]
path = "checkmark-square.svg"
SPDX-FileCopyrightText = "Copyright (c) 2020 Microsoft Corporation"
SPDX-License-Identifier = "MIT"

[[annotations]]
path = "dismiss-circle.svg"
SPDX-FileCopyrightText = "Copyright (c) 2020 Microsoft Corporation"
SPDX-License-Identifier = "MIT"

[[annotations]]
path = "dismiss-square.svg"
SPDX-FileCopyrightText = "Copyright (c) 2020 Microsoft Corporation"
SPDX-License-Identifier = "MIT"
