#include "qlogging.hpp"

Q_LOGGING_CATEGORY(chatterinoApp, "chatterino.app");
Q_LOGGING_CATEGORY(chatterinoArgs, "chatterino.args");
Q_LOGGING_CATEGORY(chatterinoBenchmark, "chatterino.benchmark");
Q_LOGGING_CATEGORY(chatterinoBttv, "chatterino.bttv");
Q_LOGGING_CATEGORY(chatterinoCommon, "chatterino.cache");
Q_LOGGING_CATEGORY(chatterinoCache, "chatterino.common");
Q_LOGGING_CATEGORY(chatterinoEmoji, "chatterino.emoji");
Q_LOGGING_CATEGORY(chatterinoFfzemotes, "chatterino.ffzemotes");
Q_LOGGING_CATEGORY(chatterinoHelper, "chatterino.helper");
Q_LOGGING_CATEGORY(chatterinoImage, "chatterino.image");
Q_LOGGING_CATEGORY(chatterinoIrc, "chatterino.irc");
Q_LOGGING_CATEGORY(chatterinoIvr, "chatterino.ivr");
Q_LOGGING_CATEGORY(chatterinoMain, "chatterino.main");
Q_LOGGING_CATEGORY(chatterinoMessage, "chatterino.message");
Q_LOGGING_CATEGORY(chatterinoNativeMessage, "chatterino.nativemessage");
Q_LOGGING_CATEGORY(chatterinoNotification, "chatterino.notification");
Q_LOGGING_CATEGORY(chatterinoNuulsuploader, "chatterino.nuulsuploader");
Q_LOGGING_CATEGORY(chatterinoPubsub, "chatterino.pubsub");
Q_LOGGING_CATEGORY(chatterinoStreamlink, "chatterino.streamlink");
Q_LOGGING_CATEGORY(chatterinoTokenizer, "chatterino.tokenizer");
Q_LOGGING_CATEGORY(chatterinoTwitch, "chatterino.twitch");
Q_LOGGING_CATEGORY(chatterinoUpdate, "chatterino.update");
Q_LOGGING_CATEGORY(chatterinoWebsocket, "chatterino.websocket");
Q_LOGGING_CATEGORY(chatterinoWidget, "chatterino.widget");
Q_LOGGING_CATEGORY(chatterinoWindowmanager, "chatterino.windowmanager");
