include_guard(GLOBAL)

find_program(CCACHE_PROGRAM ccache)
find_program(SCCACHE_PROGRAM sccache)
if (SCCACHE_PROGRAM)
    set(CCACHE_COMPILER_LAUNCHER ${SCCACHE_PROGRAM})
elseif (CCACHE_PROGRAM)
    set(CCACHE_COMPILER_LAUNCHER ${CCACHE_PROGRAM})
endif()

if (CCACHE_COMPILER_LAUNCHER)
    message(STATUS "Overriding ${CMAKE_CXX_COMPILER_LAUNCHER} with ${CCACHE_COMPILER_LAUNCHER} for faster incremental builds")
    set(CMAKE_CXX_COMPILER_LAUNCHER "${CCACHE_COMPILER_LAUNCHER}" CACHE STRING "CXX compiler launcher")

    if (MSVC)
        # /Zi can't be used with (s)ccache
        # Use /Z7 instead (debug info in object files)
        if(CMAKE_BUILD_TYPE STREQUAL "Debug")
            string(REPLACE "/Zi" "/Z7" CMAKE_CXX_FLAGS_DEBUG "${CMAKE_CXX_FLAGS_DEBUG}")
        elseif(CMAKE_BUILD_TYPE STREQUAL "Release")
            string(REPLACE "/Zi" "/Z7" CMAKE_CXX_FLAGS_RELEASE "${CMAKE_CXX_FLAGS_RELEASE}")
        elseif(CMAKE_BUILD_TYPE STREQUAL "RelWithDebInfo")
            string(REPLACE "/Zi" "/Z7" CMAKE_CXX_FLAGS_RELWITHDEBINFO "${CMAKE_CXX_FLAGS_RELWITHDEBINFO}")
        endif()
    endif()
else()
    message(STATUS "ccache not found. For faster builds, install ccache or sccache.")
endif()
