---
name: Lint

on:
  push:
    branches:
      - master
  pull_request:
  merge_group:

concurrency:
  group: lint-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0

      - name: Check formatting with Prettier
        run: |
          npx prettier@3.8.1 --write .
      - name: Show diff
        run: git --no-pager diff --exit-code --color=never
        shell: bash
      - name: Check Theme files
        run: |
          npm i ajv-cli
          npx -- ajv validate -s docs/ChatterinoTheme.schema.json -d "resources/themes/*.json"
