name: Publish to WinGet
on:
  release:
    types: [released]
jobs:
  publish:
    runs-on: windows-latest
    if: ${{ startsWith(github.event.release.tag_name, 'v') }} && github.repository_owner == 'Chatterino'
    steps:
      - uses: vedantmgoyal9/winget-releaser@a8fff44b123f115ce4c21543edf8b677376fc7e0 # main
        with:
          identifier: ChatterinoTeam.Chatterino
          installers-regex: ^Chatterino.Installer.exe$
          token: ${{ secrets.WINGET_TOKEN }}
          fork-user: chatterino-ci
